/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './DynamicComponentModule';
import * as import2 from '@angular/core/src/di/injector';
class DynamicComponentModuleInjector extends import0.NgModuleInjector<import1.DynamicComponentModule> {
  _DynamicComponentModule_0:import1.DynamicComponentModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.DynamicComponentModule {
    this._DynamicComponentModule_0 = new import1.DynamicComponentModule();
    return this._DynamicComponentModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.DynamicComponentModule)) { return this._DynamicComponentModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DynamicComponentModuleNgFactory:import0.NgModuleFactory<import1.DynamicComponentModule> = new import0.NgModuleFactory(DynamicComponentModuleInjector,import1.DynamicComponentModule);